# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.srcs/sources_1/ip/blk_mem_gen_17/blk_mem_gen_17.xci
# IP: The module: 'blk_mem_gen_17' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.gen/sources_1/ip/blk_mem_gen_17/blk_mem_gen_17_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_17'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.srcs/sources_1/ip/blk_mem_gen_17/blk_mem_gen_17.xci
# IP: The module: 'blk_mem_gen_17' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.gen/sources_1/ip/blk_mem_gen_17/blk_mem_gen_17_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_17'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
