# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.srcs/sources_1/ip/clkDVIprescaler/clkDVIprescaler.xci
# IP: The module: 'clkDVIprescaler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.gen/sources_1/ip/clkDVIprescaler/clkDVIprescaler_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkDVIprescaler'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.gen/sources_1/ip/clkDVIprescaler/clkDVIprescaler.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkDVIprescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.gen/sources_1/ip/clkDVIprescaler/clkDVIprescaler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkDVIprescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.srcs/sources_1/ip/clkDVIprescaler/clkDVIprescaler.xci
# IP: The module: 'clkDVIprescaler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.gen/sources_1/ip/clkDVIprescaler/clkDVIprescaler_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkDVIprescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.gen/sources_1/ip/clkDVIprescaler/clkDVIprescaler.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkDVIprescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Progh/Code/Project_RetroGame/Oplevering/EindProject_FPGA.gen/sources_1/ip/clkDVIprescaler/clkDVIprescaler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkDVIprescaler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
